import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Plus, Pencil } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageHeader, SearchBox, DemoBadge, Loading, Empty, Pill } from "@/components/erp/common"; import { useCan } from "@/lib/session"; import { num } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/_shell/materials")({ head: () => ({ meta: [{ title: "Materials — KK Group ERP" }, { name: "description", content: "Construction material master and reorder controls." }, { property: "og:title", content: "Materials — KK Group ERP" }, { property: "og:description", content: "Construction material master and reorder controls." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Materials });
type Row={id:string;code:string;name:string;description:string|null;hsn_sac:string|null;minimum_stock:number;reorder_level:number;maximum_stock:number|null;status:"active"|"inactive";is_demo:boolean;category_id:string;unit_id:string;item_categories:{name:string}|null;units_of_measure:{code:string}|null};
const empty={code:"",name:"",category_id:"",unit_id:"",description:"",hsn_sac:"",minimum_stock:"0",reorder_level:"0",maximum_stock:"",status:"active" as const};
function Materials(){const can=useCan(),qc=useQueryClient();const[search,setSearch]=useState(""),[page,setPage]=useState(0),[open,setOpen]=useState(false),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState(empty);
 const refs=useQuery({queryKey:["material-refs"],queryFn:async()=>{const[c,u]=await Promise.all([supabase.from("item_categories").select("id,name").eq("status","active").order("name"),supabase.from("units_of_measure").select("id,code,name").eq("status","active").order("code")]);if(c.error)throw c.error;if(u.error)throw u.error;return{categories:c.data,units:u.data}}});
 const q=useQuery({queryKey:["materials",search,page],queryFn:async()=>{let req=supabase.from("items").select("id,code,name,description,hsn_sac,minimum_stock,reorder_level,maximum_stock,status,is_demo,category_id,unit_id,item_categories(name),units_of_measure(code)",{count:"exact"}).order("name").range(page*10,page*10+9);if(search)req=req.or(`name.ilike.%${search}%,code.ilike.%${search}%,hsn_sac.ilike.%${search}%`);const r=await req;if(r.error)throw r.error;return{rows:r.data as unknown as Row[],count:r.count??0}}});
 const save=useMutation({mutationFn:async()=>{const{data:company}=await supabase.from("companies").select("id").limit(1).single();if(!company)throw new Error("Company is unavailable.");const payload={company_id:company.id,code:form.code,name:form.name,category_id:form.category_id,unit_id:form.unit_id,description:form.description||null,hsn_sac:form.hsn_sac||null,minimum_stock:Number(form.minimum_stock),reorder_level:Number(form.reorder_level),maximum_stock:form.maximum_stock?Number(form.maximum_stock):null,status:form.status};const r=editing?await supabase.from("items").update(payload).eq("id",editing.id):await supabase.from("items").insert(payload);if(r.error)throw r.error},onSuccess:()=>{qc.invalidateQueries({queryKey:["materials"]});setOpen(false);toast.success(editing?"Material updated":"Material created")},onError:e=>toast.error(e.message)});
 function show(r?:Row){setEditing(r??null);setForm(r?{code:r.code,name:r.name,category_id:r.category_id,unit_id:r.unit_id,description:r.description??"",hsn_sac:r.hsn_sac??"",minimum_stock:String(r.minimum_stock),reorder_level:String(r.reorder_level),maximum_stock:r.maximum_stock==null?"":String(r.maximum_stock),status:r.status}:empty);setOpen(true)}
 if(q.isLoading)return <Loading/>;return <><PageHeader title="Materials" subtitle={`${q.data?.count??0} materials with controlled units and reorder levels`} actions={can("materials.manage")&&<Button size="sm" onClick={()=>show()}><Plus className="h-4 w-4"/>New material</Button>}/><div className="mb-3"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(0)}} placeholder="Search code, material or HSN"/></div><div className="overflow-x-auto rounded-md border bg-card"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-left text-xs text-muted-foreground"><tr>{["Material","Category","Unit","HSN/SAC","Minimum","Reorder","Maximum","Status",""] .map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{q.data?.rows.map(r=><tr className="border-t" key={r.id}><td className="px-3 py-2"><div className="flex items-center gap-2 font-medium">{r.name}{r.is_demo&&<DemoBadge/>}</div><div className="font-mono text-xs text-muted-foreground">{r.code}</div></td><td className="px-3 py-2">{r.item_categories?.name}</td><td className="px-3 py-2 font-mono">{r.units_of_measure?.code}</td><td className="px-3 py-2 font-mono text-xs">{r.hsn_sac||"—"}</td><td className="px-3 py-2 font-mono">{num(r.minimum_stock)}</td><td className="px-3 py-2 font-mono">{num(r.reorder_level)}</td><td className="px-3 py-2 font-mono">{num(r.maximum_stock)}</td><td className="px-3 py-2"><Pill>{r.status}</Pill></td><td className="px-3 py-2">{can("materials.manage")&&<Button variant="ghost" size="icon" onClick={()=>show(r)} aria-label={`Edit ${r.name}`}><Pencil className="h-4 w-4"/></Button>}</td></tr>)}</tbody></table>{!q.data?.rows.length&&<Empty>No materials match this search.</Empty>}</div><div className="mt-3 flex justify-end gap-2"><Button variant="outline" size="sm" disabled={!page} onClick={()=>setPage(page-1)}>Previous</Button><span className="self-center text-xs text-muted-foreground">Page {page+1}</span><Button variant="outline" size="sm" disabled={(page+1)*10>=(q.data?.count??0)} onClick={()=>setPage(page+1)}>Next</Button></div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editing?"Edit material":"New material"}</DialogTitle><DialogDescription>Stock thresholds are master settings; quantities begin with approved inventory transactions.</DialogDescription></DialogHeader><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate()}}><div><Label>Item code</Label><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></div><div><Label>Item name</Label><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Category</Label><select required className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Select category</option>{refs.data?.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Unit</Label><select required className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">Select unit</option>{refs.data?.units.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><div><Label>HSN/SAC</Label><Input value={form.hsn_sac} onChange={e=>setForm({...form,hsn_sac:e.target.value})}/></div><div><Label>Description</Label><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><Label>Minimum stock</Label><Input type="number" min="0" step="0.001" value={form.minimum_stock} onChange={e=>setForm({...form,minimum_stock:e.target.value})}/></div><div><Label>Reorder level</Label><Input type="number" min="0" step="0.001" value={form.reorder_level} onChange={e=>setForm({...form,reorder_level:e.target.value})}/></div><div><Label>Maximum stock</Label><Input type="number" min="0" step="0.001" value={form.maximum_stock} onChange={e=>setForm({...form,maximum_stock:e.target.value})}/></div><div><Label>Status</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e=>setForm({...form,status:e.target.value as "active"|"inactive"})}><option value="active">Active</option><option value="inactive">Inactive</option></select></div><DialogFooter className="sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}>Save material</Button></DialogFooter></form></DialogContent></Dialog></>}