import { safeSearch } from "@/lib/utils";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Plus, Pencil } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageHeader, SearchBox, DemoBadge, Loading, Empty, Pill } from "@/components/erp/common";
import { useCan } from "@/lib/session";

export const Route = createFileRoute("/_authenticated/_shell/vendors")({ head: () => ({ meta: [{ title: "Vendors — KK Group ERP" }, { name: "description", content: "Approved vendor master for procurement." }, { property: "og:title", content: "Vendors — KK Group ERP" }, { property: "og:description", content: "Approved vendor master for procurement." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Vendors });
type Vendor = { id: string; code: string; company_name: string; contact_person: string | null; mobile: string | null; email: string | null; gstin: string | null; payment_terms_days: number; status: "active" | "inactive"; is_demo: boolean };
type VendorForm = { code:string; company_name:string; contact_person:string; mobile:string; email:string; gstin:string; payment_terms_days:string; status:"active"|"inactive" };
const blank: VendorForm = { code: "", company_name: "", contact_person: "", mobile: "", email: "", gstin: "", payment_terms_days: "30", status: "active" };

function Vendors() {
  const can = useCan(); const qc = useQueryClient(); const [search, setSearch] = useState(""); const [page, setPage] = useState(0); const [editing, setEditing] = useState<Vendor | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState(blank);
  const q = useQuery({ queryKey: ["vendors", search, page], queryFn: async () => { let req = supabase.from("vendors").select("id,code,company_name,contact_person,mobile,email,gstin,payment_terms_days,status,is_demo", { count: "exact" }).order("company_name").range(page * 10, page * 10 + 9); const s = safeSearch(search); if (s) req = req.or(`company_name.ilike.%${s}%,code.ilike.%${s}%,gstin.ilike.%${s}%`); const r = await req; if (r.error) throw r.error; return { rows: r.data as Vendor[], count: r.count ?? 0 }; } });
  const save = useMutation({ mutationFn: async () => { const { data: company } = await supabase.from("companies").select("id").limit(1).single(); if (!company) throw new Error("Company is unavailable."); const payload = { ...form, payment_terms_days: Number(form.payment_terms_days), gstin: form.gstin || null, company_id: company.id }; const r = editing ? await supabase.from("vendors").update(payload).eq("id", editing.id) : await supabase.from("vendors").insert(payload); if (r.error) throw r.error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["vendors"] }); setOpen(false); toast.success(editing ? "Vendor updated" : "Vendor created"); }, onError: (e) => toast.error(e.message) });
  function show(v?: Vendor) { setEditing(v ?? null); setForm(v ? { code: v.code, company_name: v.company_name, contact_person: v.contact_person ?? "", mobile: v.mobile ?? "", email: v.email ?? "", gstin: v.gstin ?? "", payment_terms_days: String(v.payment_terms_days), status: v.status } : blank); setOpen(true); }
  if (q.isLoading) return <Loading />;
  return <><PageHeader title="Vendors" subtitle={`${q.data?.count ?? 0} suppliers in the approved master`} actions={can("vendors.manage") && <Button size="sm" onClick={() => show()}><Plus className="h-4 w-4" />New vendor</Button>} /><div className="mb-3"><SearchBox value={search} onChange={(v) => { setSearch(v); setPage(0); }} placeholder="Search vendor, code or GSTIN" /></div><div className="doc-table overflow-x-auto rounded-xl border bg-card shadow-card [&_td]:whitespace-nowrap"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-left text-xs text-muted-foreground"><tr>{["Vendor","Contact","GSTIN","Terms","Status",""] .map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{q.data?.rows.map(v=><tr key={v.id} className="border-t"><td className="px-3 py-2"><div className="flex items-center gap-2 font-medium">{v.company_name}{v.is_demo&&<DemoBadge />}</div><div className="font-mono text-xs text-muted-foreground">{v.code}</div></td><td className="px-3 py-2">{v.contact_person || "—"}<div className="text-xs text-muted-foreground">{v.mobile || v.email}</div></td><td className="px-3 py-2 font-mono text-xs">{v.gstin || "—"}</td><td className="px-3 py-2">{v.payment_terms_days} days</td><td className="px-3 py-2"><Pill>{v.status}</Pill></td><td className="px-3 py-2 text-right">{can("vendors.manage")&&<Button variant="ghost" size="icon" onClick={() => show(v)} aria-label={`Edit ${v.company_name}`}><Pencil className="h-4 w-4" /></Button>}</td></tr>)}</tbody></table>{!q.data?.rows.length&&<Empty>No vendors match this search.</Empty>}</div><div className="mt-3 flex items-center justify-end gap-2"><Button variant="outline" size="sm" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><span className="text-xs text-muted-foreground">Page {page+1}</span><Button variant="outline" size="sm" disabled={(page+1)*10 >= (q.data?.count??0)} onClick={()=>setPage(page+1)}>Next</Button></div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?"Edit vendor":"New vendor"}</DialogTitle><DialogDescription>Maintain the supplier identity and payment terms used by procurement.</DialogDescription></DialogHeader><form onSubmit={(e)=>{e.preventDefault();save.mutate();}} className="grid gap-3 sm:grid-cols-2"><div><Label>Vendor code</Label><Input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} /></div><div><Label>Company name</Label><Input required value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})} /></div><div><Label>Contact person</Label><Input value={form.contact_person} onChange={e=>setForm({...form,contact_person:e.target.value})} /></div><div><Label>Mobile</Label><Input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} /></div><div><Label>Email</Label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} /></div><div><Label>GSTIN</Label><Input value={form.gstin} onChange={e=>setForm({...form,gstin:e.target.value.toUpperCase()})} /></div><div><Label>Payment terms (days)</Label><Input type="number" min="0" max="365" value={form.payment_terms_days} onChange={e=>setForm({...form,payment_terms_days:e.target.value})} /></div><div><Label>Status</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e=>setForm({...form,status:e.target.value as "active"|"inactive"})}><option value="active">Active</option><option value="inactive">Inactive</option></select></div><DialogFooter className="sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" disabled={save.isPending}>Save vendor</Button></DialogFooter></form></DialogContent></Dialog></>;
}