/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellAuditRouteImport } from './routes/_authenticated/_shell/audit'
import { Route as AuthenticatedShellBuildingsRouteImport } from './routes/_authenticated/_shell/buildings'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellMaterialsRouteImport } from './routes/_authenticated/_shell/materials'
import { Route as AuthenticatedShellProjectsRouteImport } from './routes/_authenticated/_shell/projects'
import { Route as AuthenticatedShellUnitsRouteImport } from './routes/_authenticated/_shell/units'
import { Route as AuthenticatedShellVendorsRouteImport } from './routes/_authenticated/_shell/vendors'
import { Route as AuthenticatedShellWarehousesRouteImport } from './routes/_authenticated/_shell/warehouses'
import { Route as AuthenticatedShellFinancePayablesRouteImport } from './routes/_authenticated/_shell/finance.payables'
import { Route as AuthenticatedShellFinancePaymentsRouteImport } from './routes/_authenticated/_shell/finance.payments'
import { Route as AuthenticatedShellFinanceVendorLedgerRouteImport } from './routes/_authenticated/_shell/finance.vendor-ledger'
import { Route as AuthenticatedShellInventoryStockRouteImport } from './routes/_authenticated/_shell/inventory.stock'
import { Route as AuthenticatedShellInventoryStockMovementsRouteImport } from './routes/_authenticated/_shell/inventory.stock-movements'
import { Route as AuthenticatedShellProcurementVendorQuotationsRouteImport } from './routes/_authenticated/_shell/procurement.vendor-quotations'
import { Route as AuthenticatedShellSettingsCompanyRouteImport } from './routes/_authenticated/_shell/settings.company'
import { Route as AuthenticatedShellSettingsFinanceRouteImport } from './routes/_authenticated/_shell/settings.finance'
import { Route as AuthenticatedShellSettingsUsersRouteImport } from './routes/_authenticated/_shell/settings.users'
import { Route as AuthenticatedShellFinanceVendorInvoicesIndexRouteImport } from './routes/_authenticated/_shell/finance.vendor-invoices.index'
import { Route as AuthenticatedShellFinanceVendorInvoicesIdRouteImport } from './routes/_authenticated/_shell/finance.vendor-invoices.$id'
import { Route as AuthenticatedShellFinanceVendorInvoicesNewRouteImport } from './routes/_authenticated/_shell/finance.vendor-invoices.new'
import { Route as AuthenticatedShellInventoryGoodsReceivedIndexRouteImport } from './routes/_authenticated/_shell/inventory.goods-received.index'
import { Route as AuthenticatedShellInventoryGoodsReceivedIdRouteImport } from './routes/_authenticated/_shell/inventory.goods-received.$id'
import { Route as AuthenticatedShellProcurementPurchaseOrdersIndexRouteImport } from './routes/_authenticated/_shell/procurement.purchase-orders.index'
import { Route as AuthenticatedShellProcurementPurchaseOrdersIdRouteImport } from './routes/_authenticated/_shell/procurement.purchase-orders.$id'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.index'
import { Route as AuthenticatedShellProcurementPurchaseRequestsNewRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.new'
import { Route as AuthenticatedShellProcurementRfqsIndexRouteImport } from './routes/_authenticated/_shell/procurement.rfqs.index'
import { Route as AuthenticatedShellProcurementRfqsNewRouteImport } from './routes/_authenticated/_shell/procurement.rfqs.new'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.$id.index'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.$id.edit'
import { Route as AuthenticatedShellProcurementRfqsIdIndexRouteImport } from './routes/_authenticated/_shell/procurement.rfqs.$id.index'
import { Route as AuthenticatedShellProcurementRfqsIdCompareRouteImport } from './routes/_authenticated/_shell/procurement.rfqs.$id.compare'
import { Route as AuthenticatedShellProcurementRfqsIdQuotationRouteImport } from './routes/_authenticated/_shell/procurement.rfqs.$id.quotation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShellAuditRoute = AuthenticatedShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellBuildingsRoute =
  AuthenticatedShellBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellMaterialsRoute =
  AuthenticatedShellMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProjectsRoute =
  AuthenticatedShellProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellUnitsRoute = AuthenticatedShellUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellVendorsRoute =
  AuthenticatedShellVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellWarehousesRoute =
  AuthenticatedShellWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinancePayablesRoute =
  AuthenticatedShellFinancePayablesRouteImport.update({
    id: '/finance/payables',
    path: '/finance/payables',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinancePaymentsRoute =
  AuthenticatedShellFinancePaymentsRouteImport.update({
    id: '/finance/payments',
    path: '/finance/payments',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinanceVendorLedgerRoute =
  AuthenticatedShellFinanceVendorLedgerRouteImport.update({
    id: '/finance/vendor-ledger',
    path: '/finance/vendor-ledger',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellInventoryStockRoute =
  AuthenticatedShellInventoryStockRouteImport.update({
    id: '/inventory/stock',
    path: '/inventory/stock',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellInventoryStockMovementsRoute =
  AuthenticatedShellInventoryStockMovementsRouteImport.update({
    id: '/inventory/stock-movements',
    path: '/inventory/stock-movements',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementVendorQuotationsRoute =
  AuthenticatedShellProcurementVendorQuotationsRouteImport.update({
    id: '/procurement/vendor-quotations',
    path: '/procurement/vendor-quotations',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsCompanyRoute =
  AuthenticatedShellSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsFinanceRoute =
  AuthenticatedShellSettingsFinanceRouteImport.update({
    id: '/settings/finance',
    path: '/settings/finance',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsUsersRoute =
  AuthenticatedShellSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinanceVendorInvoicesIndexRoute =
  AuthenticatedShellFinanceVendorInvoicesIndexRouteImport.update({
    id: '/finance/vendor-invoices/',
    path: '/finance/vendor-invoices/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinanceVendorInvoicesIdRoute =
  AuthenticatedShellFinanceVendorInvoicesIdRouteImport.update({
    id: '/finance/vendor-invoices/$id',
    path: '/finance/vendor-invoices/$id',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellFinanceVendorInvoicesNewRoute =
  AuthenticatedShellFinanceVendorInvoicesNewRouteImport.update({
    id: '/finance/vendor-invoices/new',
    path: '/finance/vendor-invoices/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellInventoryGoodsReceivedIndexRoute =
  AuthenticatedShellInventoryGoodsReceivedIndexRouteImport.update({
    id: '/inventory/goods-received/',
    path: '/inventory/goods-received/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellInventoryGoodsReceivedIdRoute =
  AuthenticatedShellInventoryGoodsReceivedIdRouteImport.update({
    id: '/inventory/goods-received/$id',
    path: '/inventory/goods-received/$id',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseOrdersIndexRoute =
  AuthenticatedShellProcurementPurchaseOrdersIndexRouteImport.update({
    id: '/procurement/purchase-orders/',
    path: '/procurement/purchase-orders/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseOrdersIdRoute =
  AuthenticatedShellProcurementPurchaseOrdersIdRouteImport.update({
    id: '/procurement/purchase-orders/$id',
    path: '/procurement/purchase-orders/$id',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIndexRoute =
  AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport.update({
    id: '/procurement/purchase-requests/',
    path: '/procurement/purchase-requests/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsNewRoute =
  AuthenticatedShellProcurementPurchaseRequestsNewRouteImport.update({
    id: '/procurement/purchase-requests/new',
    path: '/procurement/purchase-requests/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementRfqsIndexRoute =
  AuthenticatedShellProcurementRfqsIndexRouteImport.update({
    id: '/procurement/rfqs/',
    path: '/procurement/rfqs/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementRfqsNewRoute =
  AuthenticatedShellProcurementRfqsNewRouteImport.update({
    id: '/procurement/rfqs/new',
    path: '/procurement/rfqs/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute =
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport.update({
    id: '/procurement/purchase-requests/$id/',
    path: '/procurement/purchase-requests/$id/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIdEditRoute =
  AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport.update({
    id: '/procurement/purchase-requests/$id/edit',
    path: '/procurement/purchase-requests/$id/edit',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementRfqsIdIndexRoute =
  AuthenticatedShellProcurementRfqsIdIndexRouteImport.update({
    id: '/procurement/rfqs/$id/',
    path: '/procurement/rfqs/$id/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementRfqsIdCompareRoute =
  AuthenticatedShellProcurementRfqsIdCompareRouteImport.update({
    id: '/procurement/rfqs/$id/compare',
    path: '/procurement/rfqs/$id/compare',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementRfqsIdQuotationRoute =
  AuthenticatedShellProcurementRfqsIdQuotationRouteImport.update({
    id: '/procurement/rfqs/$id/quotation',
    path: '/procurement/rfqs/$id/quotation',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedShellAuditRoute
  '/buildings': typeof AuthenticatedShellBuildingsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/materials': typeof AuthenticatedShellMaterialsRoute
  '/projects': typeof AuthenticatedShellProjectsRoute
  '/units': typeof AuthenticatedShellUnitsRoute
  '/vendors': typeof AuthenticatedShellVendorsRoute
  '/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/finance/payables': typeof AuthenticatedShellFinancePayablesRoute
  '/finance/payments': typeof AuthenticatedShellFinancePaymentsRoute
  '/finance/vendor-ledger': typeof AuthenticatedShellFinanceVendorLedgerRoute
  '/inventory/stock': typeof AuthenticatedShellInventoryStockRoute
  '/inventory/stock-movements': typeof AuthenticatedShellInventoryStockMovementsRoute
  '/procurement/vendor-quotations': typeof AuthenticatedShellProcurementVendorQuotationsRoute
  '/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/settings/finance': typeof AuthenticatedShellSettingsFinanceRoute
  '/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/finance/vendor-invoices/$id': typeof AuthenticatedShellFinanceVendorInvoicesIdRoute
  '/finance/vendor-invoices/new': typeof AuthenticatedShellFinanceVendorInvoicesNewRoute
  '/inventory/goods-received/$id': typeof AuthenticatedShellInventoryGoodsReceivedIdRoute
  '/procurement/purchase-orders/$id': typeof AuthenticatedShellProcurementPurchaseOrdersIdRoute
  '/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/procurement/rfqs/new': typeof AuthenticatedShellProcurementRfqsNewRoute
  '/finance/vendor-invoices/': typeof AuthenticatedShellFinanceVendorInvoicesIndexRoute
  '/inventory/goods-received/': typeof AuthenticatedShellInventoryGoodsReceivedIndexRoute
  '/procurement/purchase-orders/': typeof AuthenticatedShellProcurementPurchaseOrdersIndexRoute
  '/procurement/purchase-requests/': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/procurement/rfqs/': typeof AuthenticatedShellProcurementRfqsIndexRoute
  '/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/procurement/rfqs/$id/compare': typeof AuthenticatedShellProcurementRfqsIdCompareRoute
  '/procurement/rfqs/$id/quotation': typeof AuthenticatedShellProcurementRfqsIdQuotationRoute
  '/procurement/purchase-requests/$id/': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
  '/procurement/rfqs/$id/': typeof AuthenticatedShellProcurementRfqsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedShellAuditRoute
  '/buildings': typeof AuthenticatedShellBuildingsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/materials': typeof AuthenticatedShellMaterialsRoute
  '/projects': typeof AuthenticatedShellProjectsRoute
  '/units': typeof AuthenticatedShellUnitsRoute
  '/vendors': typeof AuthenticatedShellVendorsRoute
  '/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/finance/payables': typeof AuthenticatedShellFinancePayablesRoute
  '/finance/payments': typeof AuthenticatedShellFinancePaymentsRoute
  '/finance/vendor-ledger': typeof AuthenticatedShellFinanceVendorLedgerRoute
  '/inventory/stock': typeof AuthenticatedShellInventoryStockRoute
  '/inventory/stock-movements': typeof AuthenticatedShellInventoryStockMovementsRoute
  '/procurement/vendor-quotations': typeof AuthenticatedShellProcurementVendorQuotationsRoute
  '/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/settings/finance': typeof AuthenticatedShellSettingsFinanceRoute
  '/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/finance/vendor-invoices/$id': typeof AuthenticatedShellFinanceVendorInvoicesIdRoute
  '/finance/vendor-invoices/new': typeof AuthenticatedShellFinanceVendorInvoicesNewRoute
  '/inventory/goods-received/$id': typeof AuthenticatedShellInventoryGoodsReceivedIdRoute
  '/procurement/purchase-orders/$id': typeof AuthenticatedShellProcurementPurchaseOrdersIdRoute
  '/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/procurement/rfqs/new': typeof AuthenticatedShellProcurementRfqsNewRoute
  '/finance/vendor-invoices': typeof AuthenticatedShellFinanceVendorInvoicesIndexRoute
  '/inventory/goods-received': typeof AuthenticatedShellInventoryGoodsReceivedIndexRoute
  '/procurement/purchase-orders': typeof AuthenticatedShellProcurementPurchaseOrdersIndexRoute
  '/procurement/purchase-requests': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/procurement/rfqs': typeof AuthenticatedShellProcurementRfqsIndexRoute
  '/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/procurement/rfqs/$id/compare': typeof AuthenticatedShellProcurementRfqsIdCompareRoute
  '/procurement/rfqs/$id/quotation': typeof AuthenticatedShellProcurementRfqsIdQuotationRoute
  '/procurement/purchase-requests/$id': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
  '/procurement/rfqs/$id': typeof AuthenticatedShellProcurementRfqsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/audit': typeof AuthenticatedShellAuditRoute
  '/_authenticated/_shell/buildings': typeof AuthenticatedShellBuildingsRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/materials': typeof AuthenticatedShellMaterialsRoute
  '/_authenticated/_shell/projects': typeof AuthenticatedShellProjectsRoute
  '/_authenticated/_shell/units': typeof AuthenticatedShellUnitsRoute
  '/_authenticated/_shell/vendors': typeof AuthenticatedShellVendorsRoute
  '/_authenticated/_shell/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/_authenticated/_shell/finance/payables': typeof AuthenticatedShellFinancePayablesRoute
  '/_authenticated/_shell/finance/payments': typeof AuthenticatedShellFinancePaymentsRoute
  '/_authenticated/_shell/finance/vendor-ledger': typeof AuthenticatedShellFinanceVendorLedgerRoute
  '/_authenticated/_shell/inventory/stock': typeof AuthenticatedShellInventoryStockRoute
  '/_authenticated/_shell/inventory/stock-movements': typeof AuthenticatedShellInventoryStockMovementsRoute
  '/_authenticated/_shell/procurement/vendor-quotations': typeof AuthenticatedShellProcurementVendorQuotationsRoute
  '/_authenticated/_shell/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/_authenticated/_shell/settings/finance': typeof AuthenticatedShellSettingsFinanceRoute
  '/_authenticated/_shell/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/_authenticated/_shell/finance/vendor-invoices/$id': typeof AuthenticatedShellFinanceVendorInvoicesIdRoute
  '/_authenticated/_shell/finance/vendor-invoices/new': typeof AuthenticatedShellFinanceVendorInvoicesNewRoute
  '/_authenticated/_shell/inventory/goods-received/$id': typeof AuthenticatedShellInventoryGoodsReceivedIdRoute
  '/_authenticated/_shell/procurement/purchase-orders/$id': typeof AuthenticatedShellProcurementPurchaseOrdersIdRoute
  '/_authenticated/_shell/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/_authenticated/_shell/procurement/rfqs/new': typeof AuthenticatedShellProcurementRfqsNewRoute
  '/_authenticated/_shell/finance/vendor-invoices/': typeof AuthenticatedShellFinanceVendorInvoicesIndexRoute
  '/_authenticated/_shell/inventory/goods-received/': typeof AuthenticatedShellInventoryGoodsReceivedIndexRoute
  '/_authenticated/_shell/procurement/purchase-orders/': typeof AuthenticatedShellProcurementPurchaseOrdersIndexRoute
  '/_authenticated/_shell/procurement/purchase-requests/': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/_authenticated/_shell/procurement/rfqs/': typeof AuthenticatedShellProcurementRfqsIndexRoute
  '/_authenticated/_shell/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/_authenticated/_shell/procurement/rfqs/$id/compare': typeof AuthenticatedShellProcurementRfqsIdCompareRoute
  '/_authenticated/_shell/procurement/rfqs/$id/quotation': typeof AuthenticatedShellProcurementRfqsIdQuotationRoute
  '/_authenticated/_shell/procurement/purchase-requests/$id/': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
  '/_authenticated/_shell/procurement/rfqs/$id/': typeof AuthenticatedShellProcurementRfqsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/buildings'
    | '/dashboard'
    | '/materials'
    | '/projects'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/finance/payables'
    | '/finance/payments'
    | '/finance/vendor-ledger'
    | '/inventory/stock'
    | '/inventory/stock-movements'
    | '/procurement/vendor-quotations'
    | '/settings/company'
    | '/settings/finance'
    | '/settings/users'
    | '/finance/vendor-invoices/$id'
    | '/finance/vendor-invoices/new'
    | '/inventory/goods-received/$id'
    | '/procurement/purchase-orders/$id'
    | '/procurement/purchase-requests/new'
    | '/procurement/rfqs/new'
    | '/finance/vendor-invoices/'
    | '/inventory/goods-received/'
    | '/procurement/purchase-orders/'
    | '/procurement/purchase-requests/'
    | '/procurement/rfqs/'
    | '/procurement/purchase-requests/$id/edit'
    | '/procurement/rfqs/$id/compare'
    | '/procurement/rfqs/$id/quotation'
    | '/procurement/purchase-requests/$id/'
    | '/procurement/rfqs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/buildings'
    | '/dashboard'
    | '/materials'
    | '/projects'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/finance/payables'
    | '/finance/payments'
    | '/finance/vendor-ledger'
    | '/inventory/stock'
    | '/inventory/stock-movements'
    | '/procurement/vendor-quotations'
    | '/settings/company'
    | '/settings/finance'
    | '/settings/users'
    | '/finance/vendor-invoices/$id'
    | '/finance/vendor-invoices/new'
    | '/inventory/goods-received/$id'
    | '/procurement/purchase-orders/$id'
    | '/procurement/purchase-requests/new'
    | '/procurement/rfqs/new'
    | '/finance/vendor-invoices'
    | '/inventory/goods-received'
    | '/procurement/purchase-orders'
    | '/procurement/purchase-requests'
    | '/procurement/rfqs'
    | '/procurement/purchase-requests/$id/edit'
    | '/procurement/rfqs/$id/compare'
    | '/procurement/rfqs/$id/quotation'
    | '/procurement/purchase-requests/$id'
    | '/procurement/rfqs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/audit'
    | '/_authenticated/_shell/buildings'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/materials'
    | '/_authenticated/_shell/projects'
    | '/_authenticated/_shell/units'
    | '/_authenticated/_shell/vendors'
    | '/_authenticated/_shell/warehouses'
    | '/_authenticated/_shell/finance/payables'
    | '/_authenticated/_shell/finance/payments'
    | '/_authenticated/_shell/finance/vendor-ledger'
    | '/_authenticated/_shell/inventory/stock'
    | '/_authenticated/_shell/inventory/stock-movements'
    | '/_authenticated/_shell/procurement/vendor-quotations'
    | '/_authenticated/_shell/settings/company'
    | '/_authenticated/_shell/settings/finance'
    | '/_authenticated/_shell/settings/users'
    | '/_authenticated/_shell/finance/vendor-invoices/$id'
    | '/_authenticated/_shell/finance/vendor-invoices/new'
    | '/_authenticated/_shell/inventory/goods-received/$id'
    | '/_authenticated/_shell/procurement/purchase-orders/$id'
    | '/_authenticated/_shell/procurement/purchase-requests/new'
    | '/_authenticated/_shell/procurement/rfqs/new'
    | '/_authenticated/_shell/finance/vendor-invoices/'
    | '/_authenticated/_shell/inventory/goods-received/'
    | '/_authenticated/_shell/procurement/purchase-orders/'
    | '/_authenticated/_shell/procurement/purchase-requests/'
    | '/_authenticated/_shell/procurement/rfqs/'
    | '/_authenticated/_shell/procurement/purchase-requests/$id/edit'
    | '/_authenticated/_shell/procurement/rfqs/$id/compare'
    | '/_authenticated/_shell/procurement/rfqs/$id/quotation'
    | '/_authenticated/_shell/procurement/purchase-requests/$id/'
    | '/_authenticated/_shell/procurement/rfqs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_shell/audit': {
      id: '/_authenticated/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedShellAuditRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/buildings': {
      id: '/_authenticated/_shell/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedShellBuildingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/materials': {
      id: '/_authenticated/_shell/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedShellMaterialsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/projects': {
      id: '/_authenticated/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedShellProjectsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/units': {
      id: '/_authenticated/_shell/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedShellUnitsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/vendors': {
      id: '/_authenticated/_shell/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedShellVendorsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/warehouses': {
      id: '/_authenticated/_shell/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedShellWarehousesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/payables': {
      id: '/_authenticated/_shell/finance/payables'
      path: '/finance/payables'
      fullPath: '/finance/payables'
      preLoaderRoute: typeof AuthenticatedShellFinancePayablesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/payments': {
      id: '/_authenticated/_shell/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AuthenticatedShellFinancePaymentsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/vendor-ledger': {
      id: '/_authenticated/_shell/finance/vendor-ledger'
      path: '/finance/vendor-ledger'
      fullPath: '/finance/vendor-ledger'
      preLoaderRoute: typeof AuthenticatedShellFinanceVendorLedgerRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inventory/stock': {
      id: '/_authenticated/_shell/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AuthenticatedShellInventoryStockRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inventory/stock-movements': {
      id: '/_authenticated/_shell/inventory/stock-movements'
      path: '/inventory/stock-movements'
      fullPath: '/inventory/stock-movements'
      preLoaderRoute: typeof AuthenticatedShellInventoryStockMovementsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/vendor-quotations': {
      id: '/_authenticated/_shell/procurement/vendor-quotations'
      path: '/procurement/vendor-quotations'
      fullPath: '/procurement/vendor-quotations'
      preLoaderRoute: typeof AuthenticatedShellProcurementVendorQuotationsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/company': {
      id: '/_authenticated/_shell/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedShellSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/finance': {
      id: '/_authenticated/_shell/settings/finance'
      path: '/settings/finance'
      fullPath: '/settings/finance'
      preLoaderRoute: typeof AuthenticatedShellSettingsFinanceRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/users': {
      id: '/_authenticated/_shell/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedShellSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/vendor-invoices/': {
      id: '/_authenticated/_shell/finance/vendor-invoices/'
      path: '/finance/vendor-invoices'
      fullPath: '/finance/vendor-invoices/'
      preLoaderRoute: typeof AuthenticatedShellFinanceVendorInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/vendor-invoices/$id': {
      id: '/_authenticated/_shell/finance/vendor-invoices/$id'
      path: '/finance/vendor-invoices/$id'
      fullPath: '/finance/vendor-invoices/$id'
      preLoaderRoute: typeof AuthenticatedShellFinanceVendorInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/finance/vendor-invoices/new': {
      id: '/_authenticated/_shell/finance/vendor-invoices/new'
      path: '/finance/vendor-invoices/new'
      fullPath: '/finance/vendor-invoices/new'
      preLoaderRoute: typeof AuthenticatedShellFinanceVendorInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inventory/goods-received/': {
      id: '/_authenticated/_shell/inventory/goods-received/'
      path: '/inventory/goods-received'
      fullPath: '/inventory/goods-received/'
      preLoaderRoute: typeof AuthenticatedShellInventoryGoodsReceivedIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/inventory/goods-received/$id': {
      id: '/_authenticated/_shell/inventory/goods-received/$id'
      path: '/inventory/goods-received/$id'
      fullPath: '/inventory/goods-received/$id'
      preLoaderRoute: typeof AuthenticatedShellInventoryGoodsReceivedIdRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-orders/': {
      id: '/_authenticated/_shell/procurement/purchase-orders/'
      path: '/procurement/purchase-orders'
      fullPath: '/procurement/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-orders/$id': {
      id: '/_authenticated/_shell/procurement/purchase-orders/$id'
      path: '/procurement/purchase-orders/$id'
      fullPath: '/procurement/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/': {
      id: '/_authenticated/_shell/procurement/purchase-requests/'
      path: '/procurement/purchase-requests'
      fullPath: '/procurement/purchase-requests/'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/new': {
      id: '/_authenticated/_shell/procurement/purchase-requests/new'
      path: '/procurement/purchase-requests/new'
      fullPath: '/procurement/purchase-requests/new'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/rfqs/': {
      id: '/_authenticated/_shell/procurement/rfqs/'
      path: '/procurement/rfqs'
      fullPath: '/procurement/rfqs/'
      preLoaderRoute: typeof AuthenticatedShellProcurementRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/rfqs/new': {
      id: '/_authenticated/_shell/procurement/rfqs/new'
      path: '/procurement/rfqs/new'
      fullPath: '/procurement/rfqs/new'
      preLoaderRoute: typeof AuthenticatedShellProcurementRfqsNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/$id/': {
      id: '/_authenticated/_shell/procurement/purchase-requests/$id/'
      path: '/procurement/purchase-requests/$id'
      fullPath: '/procurement/purchase-requests/$id/'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/$id/edit': {
      id: '/_authenticated/_shell/procurement/purchase-requests/$id/edit'
      path: '/procurement/purchase-requests/$id/edit'
      fullPath: '/procurement/purchase-requests/$id/edit'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/rfqs/$id/': {
      id: '/_authenticated/_shell/procurement/rfqs/$id/'
      path: '/procurement/rfqs/$id'
      fullPath: '/procurement/rfqs/$id/'
      preLoaderRoute: typeof AuthenticatedShellProcurementRfqsIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/rfqs/$id/compare': {
      id: '/_authenticated/_shell/procurement/rfqs/$id/compare'
      path: '/procurement/rfqs/$id/compare'
      fullPath: '/procurement/rfqs/$id/compare'
      preLoaderRoute: typeof AuthenticatedShellProcurementRfqsIdCompareRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/rfqs/$id/quotation': {
      id: '/_authenticated/_shell/procurement/rfqs/$id/quotation'
      path: '/procurement/rfqs/$id/quotation'
      fullPath: '/procurement/rfqs/$id/quotation'
      preLoaderRoute: typeof AuthenticatedShellProcurementRfqsIdQuotationRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAuditRoute: typeof AuthenticatedShellAuditRoute
  AuthenticatedShellBuildingsRoute: typeof AuthenticatedShellBuildingsRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellMaterialsRoute: typeof AuthenticatedShellMaterialsRoute
  AuthenticatedShellProjectsRoute: typeof AuthenticatedShellProjectsRoute
  AuthenticatedShellUnitsRoute: typeof AuthenticatedShellUnitsRoute
  AuthenticatedShellVendorsRoute: typeof AuthenticatedShellVendorsRoute
  AuthenticatedShellWarehousesRoute: typeof AuthenticatedShellWarehousesRoute
  AuthenticatedShellFinancePayablesRoute: typeof AuthenticatedShellFinancePayablesRoute
  AuthenticatedShellFinancePaymentsRoute: typeof AuthenticatedShellFinancePaymentsRoute
  AuthenticatedShellFinanceVendorLedgerRoute: typeof AuthenticatedShellFinanceVendorLedgerRoute
  AuthenticatedShellInventoryStockRoute: typeof AuthenticatedShellInventoryStockRoute
  AuthenticatedShellInventoryStockMovementsRoute: typeof AuthenticatedShellInventoryStockMovementsRoute
  AuthenticatedShellProcurementVendorQuotationsRoute: typeof AuthenticatedShellProcurementVendorQuotationsRoute
  AuthenticatedShellSettingsCompanyRoute: typeof AuthenticatedShellSettingsCompanyRoute
  AuthenticatedShellSettingsFinanceRoute: typeof AuthenticatedShellSettingsFinanceRoute
  AuthenticatedShellSettingsUsersRoute: typeof AuthenticatedShellSettingsUsersRoute
  AuthenticatedShellFinanceVendorInvoicesIdRoute: typeof AuthenticatedShellFinanceVendorInvoicesIdRoute
  AuthenticatedShellFinanceVendorInvoicesNewRoute: typeof AuthenticatedShellFinanceVendorInvoicesNewRoute
  AuthenticatedShellInventoryGoodsReceivedIdRoute: typeof AuthenticatedShellInventoryGoodsReceivedIdRoute
  AuthenticatedShellProcurementPurchaseOrdersIdRoute: typeof AuthenticatedShellProcurementPurchaseOrdersIdRoute
  AuthenticatedShellProcurementPurchaseRequestsNewRoute: typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  AuthenticatedShellProcurementRfqsNewRoute: typeof AuthenticatedShellProcurementRfqsNewRoute
  AuthenticatedShellFinanceVendorInvoicesIndexRoute: typeof AuthenticatedShellFinanceVendorInvoicesIndexRoute
  AuthenticatedShellInventoryGoodsReceivedIndexRoute: typeof AuthenticatedShellInventoryGoodsReceivedIndexRoute
  AuthenticatedShellProcurementPurchaseOrdersIndexRoute: typeof AuthenticatedShellProcurementPurchaseOrdersIndexRoute
  AuthenticatedShellProcurementPurchaseRequestsIndexRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  AuthenticatedShellProcurementRfqsIndexRoute: typeof AuthenticatedShellProcurementRfqsIndexRoute
  AuthenticatedShellProcurementPurchaseRequestsIdEditRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  AuthenticatedShellProcurementRfqsIdCompareRoute: typeof AuthenticatedShellProcurementRfqsIdCompareRoute
  AuthenticatedShellProcurementRfqsIdQuotationRoute: typeof AuthenticatedShellProcurementRfqsIdQuotationRoute
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
  AuthenticatedShellProcurementRfqsIdIndexRoute: typeof AuthenticatedShellProcurementRfqsIdIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAuditRoute: AuthenticatedShellAuditRoute,
  AuthenticatedShellBuildingsRoute: AuthenticatedShellBuildingsRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellMaterialsRoute: AuthenticatedShellMaterialsRoute,
  AuthenticatedShellProjectsRoute: AuthenticatedShellProjectsRoute,
  AuthenticatedShellUnitsRoute: AuthenticatedShellUnitsRoute,
  AuthenticatedShellVendorsRoute: AuthenticatedShellVendorsRoute,
  AuthenticatedShellWarehousesRoute: AuthenticatedShellWarehousesRoute,
  AuthenticatedShellFinancePayablesRoute:
    AuthenticatedShellFinancePayablesRoute,
  AuthenticatedShellFinancePaymentsRoute:
    AuthenticatedShellFinancePaymentsRoute,
  AuthenticatedShellFinanceVendorLedgerRoute:
    AuthenticatedShellFinanceVendorLedgerRoute,
  AuthenticatedShellInventoryStockRoute: AuthenticatedShellInventoryStockRoute,
  AuthenticatedShellInventoryStockMovementsRoute:
    AuthenticatedShellInventoryStockMovementsRoute,
  AuthenticatedShellProcurementVendorQuotationsRoute:
    AuthenticatedShellProcurementVendorQuotationsRoute,
  AuthenticatedShellSettingsCompanyRoute:
    AuthenticatedShellSettingsCompanyRoute,
  AuthenticatedShellSettingsFinanceRoute:
    AuthenticatedShellSettingsFinanceRoute,
  AuthenticatedShellSettingsUsersRoute: AuthenticatedShellSettingsUsersRoute,
  AuthenticatedShellFinanceVendorInvoicesIdRoute:
    AuthenticatedShellFinanceVendorInvoicesIdRoute,
  AuthenticatedShellFinanceVendorInvoicesNewRoute:
    AuthenticatedShellFinanceVendorInvoicesNewRoute,
  AuthenticatedShellInventoryGoodsReceivedIdRoute:
    AuthenticatedShellInventoryGoodsReceivedIdRoute,
  AuthenticatedShellProcurementPurchaseOrdersIdRoute:
    AuthenticatedShellProcurementPurchaseOrdersIdRoute,
  AuthenticatedShellProcurementPurchaseRequestsNewRoute:
    AuthenticatedShellProcurementPurchaseRequestsNewRoute,
  AuthenticatedShellProcurementRfqsNewRoute:
    AuthenticatedShellProcurementRfqsNewRoute,
  AuthenticatedShellFinanceVendorInvoicesIndexRoute:
    AuthenticatedShellFinanceVendorInvoicesIndexRoute,
  AuthenticatedShellInventoryGoodsReceivedIndexRoute:
    AuthenticatedShellInventoryGoodsReceivedIndexRoute,
  AuthenticatedShellProcurementPurchaseOrdersIndexRoute:
    AuthenticatedShellProcurementPurchaseOrdersIndexRoute,
  AuthenticatedShellProcurementPurchaseRequestsIndexRoute:
    AuthenticatedShellProcurementPurchaseRequestsIndexRoute,
  AuthenticatedShellProcurementRfqsIndexRoute:
    AuthenticatedShellProcurementRfqsIndexRoute,
  AuthenticatedShellProcurementPurchaseRequestsIdEditRoute:
    AuthenticatedShellProcurementPurchaseRequestsIdEditRoute,
  AuthenticatedShellProcurementRfqsIdCompareRoute:
    AuthenticatedShellProcurementRfqsIdCompareRoute,
  AuthenticatedShellProcurementRfqsIdQuotationRoute:
    AuthenticatedShellProcurementRfqsIdQuotationRoute,
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute:
    AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute,
  AuthenticatedShellProcurementRfqsIdIndexRoute:
    AuthenticatedShellProcurementRfqsIdIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
