/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedShellAuditRouteImport } from './routes/_authenticated/_shell/audit'
import { Route as AuthenticatedShellBuildingsRouteImport } from './routes/_authenticated/_shell/buildings'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellMaterialsRouteImport } from './routes/_authenticated/_shell/materials'
import { Route as AuthenticatedShellProjectsRouteImport } from './routes/_authenticated/_shell/projects'
import { Route as AuthenticatedShellUnitsRouteImport } from './routes/_authenticated/_shell/units'
import { Route as AuthenticatedShellVendorsRouteImport } from './routes/_authenticated/_shell/vendors'
import { Route as AuthenticatedShellWarehousesRouteImport } from './routes/_authenticated/_shell/warehouses'
import { Route as AuthenticatedShellSettingsCompanyRouteImport } from './routes/_authenticated/_shell/settings.company'
import { Route as AuthenticatedShellSettingsUsersRouteImport } from './routes/_authenticated/_shell/settings.users'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.index'
import { Route as AuthenticatedShellProcurementPurchaseRequestsNewRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.new'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.$id.index'
import { Route as AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport } from './routes/_authenticated/_shell/procurement.purchase-requests.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShellAuditRoute = AuthenticatedShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellBuildingsRoute =
  AuthenticatedShellBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellMaterialsRoute =
  AuthenticatedShellMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProjectsRoute =
  AuthenticatedShellProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellUnitsRoute = AuthenticatedShellUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellVendorsRoute =
  AuthenticatedShellVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellWarehousesRoute =
  AuthenticatedShellWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsCompanyRoute =
  AuthenticatedShellSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsUsersRoute =
  AuthenticatedShellSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIndexRoute =
  AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport.update({
    id: '/procurement/purchase-requests/',
    path: '/procurement/purchase-requests/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsNewRoute =
  AuthenticatedShellProcurementPurchaseRequestsNewRouteImport.update({
    id: '/procurement/purchase-requests/new',
    path: '/procurement/purchase-requests/new',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute =
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport.update({
    id: '/procurement/purchase-requests/$id/',
    path: '/procurement/purchase-requests/$id/',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellProcurementPurchaseRequestsIdEditRoute =
  AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport.update({
    id: '/procurement/purchase-requests/$id/edit',
    path: '/procurement/purchase-requests/$id/edit',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedShellAuditRoute
  '/buildings': typeof AuthenticatedShellBuildingsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/materials': typeof AuthenticatedShellMaterialsRoute
  '/projects': typeof AuthenticatedShellProjectsRoute
  '/units': typeof AuthenticatedShellUnitsRoute
  '/vendors': typeof AuthenticatedShellVendorsRoute
  '/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/procurement/purchase-requests/': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/procurement/purchase-requests/$id/': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedShellAuditRoute
  '/buildings': typeof AuthenticatedShellBuildingsRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/materials': typeof AuthenticatedShellMaterialsRoute
  '/projects': typeof AuthenticatedShellProjectsRoute
  '/units': typeof AuthenticatedShellUnitsRoute
  '/vendors': typeof AuthenticatedShellVendorsRoute
  '/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/procurement/purchase-requests': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/procurement/purchase-requests/$id': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/audit': typeof AuthenticatedShellAuditRoute
  '/_authenticated/_shell/buildings': typeof AuthenticatedShellBuildingsRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/materials': typeof AuthenticatedShellMaterialsRoute
  '/_authenticated/_shell/projects': typeof AuthenticatedShellProjectsRoute
  '/_authenticated/_shell/units': typeof AuthenticatedShellUnitsRoute
  '/_authenticated/_shell/vendors': typeof AuthenticatedShellVendorsRoute
  '/_authenticated/_shell/warehouses': typeof AuthenticatedShellWarehousesRoute
  '/_authenticated/_shell/settings/company': typeof AuthenticatedShellSettingsCompanyRoute
  '/_authenticated/_shell/settings/users': typeof AuthenticatedShellSettingsUsersRoute
  '/_authenticated/_shell/procurement/purchase-requests/new': typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  '/_authenticated/_shell/procurement/purchase-requests/': typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  '/_authenticated/_shell/procurement/purchase-requests/$id/edit': typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  '/_authenticated/_shell/procurement/purchase-requests/$id/': typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/buildings'
    | '/dashboard'
    | '/materials'
    | '/projects'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/settings/company'
    | '/settings/users'
    | '/procurement/purchase-requests/new'
    | '/procurement/purchase-requests/'
    | '/procurement/purchase-requests/$id/edit'
    | '/procurement/purchase-requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/buildings'
    | '/dashboard'
    | '/materials'
    | '/projects'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/settings/company'
    | '/settings/users'
    | '/procurement/purchase-requests/new'
    | '/procurement/purchase-requests'
    | '/procurement/purchase-requests/$id/edit'
    | '/procurement/purchase-requests/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/audit'
    | '/_authenticated/_shell/buildings'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/materials'
    | '/_authenticated/_shell/projects'
    | '/_authenticated/_shell/units'
    | '/_authenticated/_shell/vendors'
    | '/_authenticated/_shell/warehouses'
    | '/_authenticated/_shell/settings/company'
    | '/_authenticated/_shell/settings/users'
    | '/_authenticated/_shell/procurement/purchase-requests/new'
    | '/_authenticated/_shell/procurement/purchase-requests/'
    | '/_authenticated/_shell/procurement/purchase-requests/$id/edit'
    | '/_authenticated/_shell/procurement/purchase-requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_shell/audit': {
      id: '/_authenticated/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedShellAuditRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/buildings': {
      id: '/_authenticated/_shell/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedShellBuildingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/materials': {
      id: '/_authenticated/_shell/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedShellMaterialsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/projects': {
      id: '/_authenticated/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedShellProjectsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/units': {
      id: '/_authenticated/_shell/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedShellUnitsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/vendors': {
      id: '/_authenticated/_shell/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedShellVendorsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/warehouses': {
      id: '/_authenticated/_shell/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedShellWarehousesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/company': {
      id: '/_authenticated/_shell/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedShellSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings/users': {
      id: '/_authenticated/_shell/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedShellSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/': {
      id: '/_authenticated/_shell/procurement/purchase-requests/'
      path: '/procurement/purchase-requests'
      fullPath: '/procurement/purchase-requests/'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/new': {
      id: '/_authenticated/_shell/procurement/purchase-requests/new'
      path: '/procurement/purchase-requests/new'
      fullPath: '/procurement/purchase-requests/new'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsNewRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/$id/': {
      id: '/_authenticated/_shell/procurement/purchase-requests/$id/'
      path: '/procurement/purchase-requests/$id'
      fullPath: '/procurement/purchase-requests/$id/'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/procurement/purchase-requests/$id/edit': {
      id: '/_authenticated/_shell/procurement/purchase-requests/$id/edit'
      path: '/procurement/purchase-requests/$id/edit'
      fullPath: '/procurement/purchase-requests/$id/edit'
      preLoaderRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAuditRoute: typeof AuthenticatedShellAuditRoute
  AuthenticatedShellBuildingsRoute: typeof AuthenticatedShellBuildingsRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellMaterialsRoute: typeof AuthenticatedShellMaterialsRoute
  AuthenticatedShellProjectsRoute: typeof AuthenticatedShellProjectsRoute
  AuthenticatedShellUnitsRoute: typeof AuthenticatedShellUnitsRoute
  AuthenticatedShellVendorsRoute: typeof AuthenticatedShellVendorsRoute
  AuthenticatedShellWarehousesRoute: typeof AuthenticatedShellWarehousesRoute
  AuthenticatedShellSettingsCompanyRoute: typeof AuthenticatedShellSettingsCompanyRoute
  AuthenticatedShellSettingsUsersRoute: typeof AuthenticatedShellSettingsUsersRoute
  AuthenticatedShellProcurementPurchaseRequestsNewRoute: typeof AuthenticatedShellProcurementPurchaseRequestsNewRoute
  AuthenticatedShellProcurementPurchaseRequestsIndexRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIndexRoute
  AuthenticatedShellProcurementPurchaseRequestsIdEditRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdEditRoute
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute: typeof AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAuditRoute: AuthenticatedShellAuditRoute,
  AuthenticatedShellBuildingsRoute: AuthenticatedShellBuildingsRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellMaterialsRoute: AuthenticatedShellMaterialsRoute,
  AuthenticatedShellProjectsRoute: AuthenticatedShellProjectsRoute,
  AuthenticatedShellUnitsRoute: AuthenticatedShellUnitsRoute,
  AuthenticatedShellVendorsRoute: AuthenticatedShellVendorsRoute,
  AuthenticatedShellWarehousesRoute: AuthenticatedShellWarehousesRoute,
  AuthenticatedShellSettingsCompanyRoute:
    AuthenticatedShellSettingsCompanyRoute,
  AuthenticatedShellSettingsUsersRoute: AuthenticatedShellSettingsUsersRoute,
  AuthenticatedShellProcurementPurchaseRequestsNewRoute:
    AuthenticatedShellProcurementPurchaseRequestsNewRoute,
  AuthenticatedShellProcurementPurchaseRequestsIndexRoute:
    AuthenticatedShellProcurementPurchaseRequestsIndexRoute,
  AuthenticatedShellProcurementPurchaseRequestsIdEditRoute:
    AuthenticatedShellProcurementPurchaseRequestsIdEditRoute,
  AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute:
    AuthenticatedShellProcurementPurchaseRequestsIdIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
